# Generated by Django 4.0.5 on 2022-06-06 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0005_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
